#+BEGIN_HTML
<img src="https://goreportcard.com/badge/github.com/lcaballero/griller" 
     tag="https://goreportcard.com/badge/github.com/lcaballero/griller" />

<a href="https://godoc.org/github.com/lcaballero/griller">
   <img src="https://godoc.org/github.com/lcaballero/griller?status.svg" alt="GoDoc"/>
</a>

<img src="https://travis-ci.org/lcaballero/griller.svg?branch=master"/>
#+END_HTML


* Introduction

=griller= creates a starter projects with some basic structure.  For
Go projects the basic structure includes command line processing using
[[https://github.com/jessevdk/go-flags][go-flags]].  For a =vue= project, the structure include =package.json=
from which npm can install dependencies.

** Installation

#+BEGIN_SRC shell
go get -u github.com/lcaballero/griller
#+END_SRC

** Usage

#+BEGIN_SRC shell
griller [OPTIONS] name project
#+END_SRC

A directory for the project will be created in the current directory
containing the boiler plate code for the project.

A =~/.griller= JSON file can be created with the default values for the
=--dest= and =--remote= flags.  For example:

#+BEGIN_SRC javascript
{
  "Remote": "github.com/saber",
  "Dest": "$GOPATH/src/github.com/saber"
}
#+END_SRC

Once the =.griller= file is present you can then run (assuming that
the griller executable is on the PATH):

#+BEGIN_SRC shell
griller go newlib
#+END_SRC

Using the above values, a new Go project will be located at
=$GOPATH/src/github.com/saber/newlib=.  Any internal =import=
statements will use the remote =github.com/saber=.  The following set
of commands should test that the boilerplate code will compile and
execute correctly.

#+BEGIN_SRC shell
%> cd $GOPATH/src/github.com/saber/newlib
%> go install
%> $GOPATH/bin/newlib
{
   "Name":""
}
#+END_SRC

The results of running the last command causes the newly compiled
executable to dump it's configuration to standard out.

** License

See license file.

The use and distribution terms for this software are covered by the
[[http://opensource.org/licenses/eclipse-1.0.txt][Eclipse Public License 1.0]], which can be found in the file
'license' at the root of this distribution. By using this software in
any fashion, you are agreeing to be bound by the terms of this
license. You must not remove this notice, or any other, from this
software.



